name: snswiki-update
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests

      - name: Execute Python script # Run the run.py to get the latest data
        run: python main.py

      - name: Stage edited files
        run: git stage .

      - name: Commit edited files
        run: |
          git config --global user.name '${{secrets.GITHUB_TOKEN}}'
          git config --global user.email '${{secrets.GITHUB_TOKEN}}'
          git commit -m "Auto-update of site metadata"

      - name: Push back files
        run: git push origin
