name: snswiki-update
run-name: ${{ github.actor }} updated SNSWiki.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests

      - name: Execute Python script # Run the run.py to get the latest data
        run: python main.py

      - name: Stage edited files
        run: git stage .

      - name: Commit edited files
        run: |
          git config --global user.name 'Graphite2213'
          git config --global user.email '88732099+Graphite2213@users.noreply.github.com'
          git commit -m "Auto-update of site metadata; Performed by ${{github.actor}}"

      - name: Push back files
        run: git push origin