name: auto-review

on: 
  pull_request_target:
    types:
      - labeled
      - submitted
  status: {}

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
    
  auto-squash:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/autosquash@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
