name: auto-review

on:
  pull_request:
    paths:
      - en/*/*
      - en/*/Images/*.jpe?g
      - en/*/Images/*.png
      - en/*/Images/*.svg
      - en/*/Images/*.webp
      - rs/*/*
      - rs/*/Images/*.jpe?g
      - rs/*/Images/*.png
      - rs/*/Images/*.svg
      - rs/*/Images/*.webp
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
      

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
    
  automerge:
    needs: labeler
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "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"
          LOG: "DEBUG"
          MERGE_LABELS: "autosquash"
          MERGE_REMOVE_LABELS: "autosquash"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
