name: auto-review

on: 
  pull_request_target

jobs:
  auto-squash:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/autosquash@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
