name: auto-review

on: 
  pull_request_target:
    paths:
      - en/*/*
      - en/*/Images/*.jpe?g
      - en/*/Images/*.png
      - en/*/Images/*.svg
      - en/*/Images/*.webp
      - rs/*/*
      - rs/*/Images/*.jpe?g
      - rs/*/Images/*.png
      - rs/*/Images/*.svg
      - rs/*/Images/*.webp
env:
  MERGE_LABELS: "autosquash"
  MERGE_REMOVE_LABELS: "autosquash"
  MERGE_METHOD: "squash"
  MERGE_COMMIT_MESSAGE: "pull-request-title"

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
    
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
