name: auto-review

on: 
  pull_request:
    paths:
      - "../../en/*"
      - "../../rs/*"

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto-approved edit made to page."
